### ISSUE TITLE
Documents with both _id and id can't be updated

### ISSUE THREAD

**Issue by Gnurfos** [bobthecow/genghis#77]
I have some documents with both an _id (mongodb's) and id field (some other app specific identifier). When trying to update a document, the wrong id is used. For example with a document containing:

_id{
  $id"511356de5ad1df09a7000002"
},
id : "foo"

The update URL looks like:
  genghis.php/servers/localhost/databases/XXX/collections/YYY/documents/foo
which 404's. The same URL with the real _id instead of "foo" works.

**Comment by bobthecow** [comment]
This used to be an issue but it should be fixed now. Are you using the newest version of Genghis?

**Comment by Gnurfos** [comment]
Ah, not at all, I had 1.4.2 (I don't know where I got it).
I just tried with 2.1.6 (the version currently downloadable on the site), but the problem is still present.
Is the fix in a yet more recent version ?

**Comment by bobthecow** [comment]
Oh, it actually looks like it's in the upcoming v2.2.0 release: https://github.com/bobthecow/genghis/blob/develop/CHANGELOG.markdown

> Handle Backbone weirdness in docs with both _id and id properties.

Sorry, I lose track of what has been released and what hasn't :)

Feel free to use the dev version. It's stable and solid. I'm not sure exactly when it will be released, but you should use the dev version in the interim.

**Comment by Gnurfos** [comment]
Indeed, that version works perfectly. Thanks !

**Comment by bobthecow** [comment]
Great!
